import { 
  UserProfile, 
  Household, 
  Visit, 
  HealthAlert, 
  EarningRecord, 
  IncentiveRule, 
  OutbreakCluster, 
  NotificationItem, 
  AuditLog,
  Patient 
} from '../types';

export const DEMO_USERS: UserProfile[] = [
  {
    uid: 'asha-1',
    name: 'Rani Devi',
    phone: '+91 98765 43210',
    email: 'rani.asha@gov.in',
    role: 'asha_worker',
    village: 'Bhopal Sector 3',
    district: 'Bhopal',
    state: 'Madhya Pradesh',
    profilePhoto: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    createdAt: '2025-01-10T08:00:00Z',
    updatedAt: '2026-08-20T08:00:00Z',
    active: true
  },
  {
    uid: 'asha-2',
    name: 'Sunita Sharma',
    phone: '+91 98765 43211',
    email: 'sunita.asha@gov.in',
    role: 'asha_worker',
    village: 'Ward 14',
    district: 'Bhopal',
    state: 'Madhya Pradesh',
    profilePhoto: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    createdAt: '2025-01-15T08:00:00Z',
    updatedAt: '2026-08-20T08:00:00Z',
    active: true
  },
  {
    uid: 'asha-3',
    name: 'Pooja Verma',
    phone: '+91 98765 43212',
    email: 'pooja.asha@gov.in',
    role: 'asha_worker',
    village: 'Kolar Road',
    district: 'Bhopal',
    state: 'Madhya Pradesh',
    createdAt: '2025-02-01T08:00:00Z',
    updatedAt: '2026-08-20T08:00:00Z',
    active: true
  },
  {
    uid: 'dho-1',
    name: 'Dr. Rajesh Sharma',
    phone: '+91 91234 56789',
    email: 'dr.sharma.dho@gov.in',
    role: 'supervisor',
    village: 'All Sectors (Bhopal HQ)',
    district: 'Bhopal',
    state: 'Madhya Pradesh',
    profilePhoto: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=150&auto=format&fit=crop&q=80',
    createdAt: '2024-11-01T08:00:00Z',
    updatedAt: '2026-08-20T08:00:00Z',
    active: true
  },
  {
    uid: 'admin-1',
    name: 'Smt. Anjali Patel (Chief Admin)',
    phone: '+91 90000 11111',
    email: 'admin.intelliashe@nhm.gov.in',
    role: 'admin',
    village: 'State Health Mission HQ',
    district: 'Bhopal',
    state: 'Madhya Pradesh',
    createdAt: '2024-10-01T08:00:00Z',
    updatedAt: '2026-08-20T08:00:00Z',
    active: true
  }
];

export const DEMO_VILLAGES = [
  { name: 'Bhopal Sector 3', lat: 23.2599, lng: 77.4126, district: 'Bhopal', population: 4200, households: 650 },
  { name: 'Ward 14', lat: 23.2650, lng: 77.4180, district: 'Bhopal', population: 3100, households: 480 },
  { name: 'Kolar Road', lat: 23.1691, lng: 77.4212, district: 'Bhopal', population: 5300, households: 820 },
  { name: 'MP Nagar', lat: 23.2314, lng: 77.4382, district: 'Bhopal', population: 2800, households: 390 },
  { name: 'Bairagarh', lat: 23.2712, lng: 77.3443, district: 'Bhopal', population: 3600, households: 510 }
];

export const DEMO_INCENTIVE_RULES: IncentiveRule[] = [
  {
    id: 'inc-1',
    taskType: 'ROUTINE_VISIT',
    title: 'Routine Household Health Survey',
    baseAmount: 50,
    bonusAmount: 15,
    description: 'General checkup, hygiene check, nutrition assessment',
    active: true
  },
  {
    id: 'inc-2',
    taskType: 'IMMUNIZATION',
    title: 'Child Immunization Tracking',
    baseAmount: 100,
    bonusAmount: 25,
    description: 'Tracking pentavalent, BCG, measles vaccines under Mission Indradhanush',
    active: true
  },
  {
    id: 'inc-3',
    taskType: 'ANC_PNC',
    title: 'Antenatal & Postnatal Checkup',
    baseAmount: 150,
    bonusAmount: 50,
    description: 'Maternal monitoring, IFA tablets distribution, institutional delivery preparation',
    active: true
  },
  {
    id: 'inc-4',
    taskType: 'HIGH_RISK_FOLLOWUP',
    title: 'High-Risk Case Escalation & Follow-up',
    baseAmount: 120,
    bonusAmount: 40,
    description: 'Timely home visit for severe malnutrition, high fever, or maternal risk',
    active: true
  },
  {
    id: 'inc-5',
    taskType: 'OUTBREAK_REPORT',
    title: 'Syndromic Outbreak Early Alert',
    baseAmount: 200,
    bonusAmount: 100,
    description: 'Reporting 3+ clustered cases of fever, diarrhea, or rash in 48 hours',
    active: true
  }
];

export const DEMO_HOUSEHOLDS: Household[] = [
  {
    id: 'hh-1',
    familyName: 'Sharma Family',
    headOfFamily: 'Manoj Sharma',
    village: 'Ramnagar',
    district: 'Varanasi',
    state: 'Uttar Pradesh',
    membersCount: 5,
    hasPregnantMother: false,
    hasInfantsUnder5: true,
    address: 'Near Old Shiva Temple, Ward 4',
    latitude: 25.2682,
    longitude: 83.0305,
    lastVisitDate: '2026-08-22T09:30:00Z',
    lastVisitSeverity: 'medium',
    notes: 'Child Rahul (3y) was experiencing fever and poor appetite.'
  },
  {
    id: 'hh-2',
    familyName: 'Yadav Family',
    headOfFamily: 'Suresh Yadav',
    village: 'Ramnagar',
    district: 'Varanasi',
    state: 'Uttar Pradesh',
    membersCount: 6,
    hasPregnantMother: true,
    hasInfantsUnder5: true,
    address: 'Plot 12, Canal Road',
    latitude: 25.2665,
    longitude: 83.0280,
    lastVisitDate: '2026-08-22T10:15:00Z',
    lastVisitSeverity: 'high',
    notes: 'Pregnant mother Geeta (3rd trimester) showing high blood pressure & pedal edema.'
  },
  {
    id: 'hh-3',
    familyName: 'Patel Family',
    headOfFamily: 'Dinesh Patel',
    village: 'Kalyanpur',
    district: 'Varanasi',
    state: 'Uttar Pradesh',
    membersCount: 4,
    hasPregnantMother: false,
    hasInfantsUnder5: true,
    address: 'House 55, Primary School Lane',
    latitude: 25.2915,
    longitude: 83.0535,
    lastVisitDate: '2026-08-21T11:45:00Z',
    lastVisitSeverity: 'low',
    notes: 'Routine 9-month immunization due next Tuesday.'
  },
  {
    id: 'hh-4',
    familyName: 'Gupta Family',
    headOfFamily: 'Ramesh Gupta',
    village: 'Shivdaspur',
    district: 'Varanasi',
    state: 'Uttar Pradesh',
    membersCount: 7,
    hasPregnantMother: false,
    hasInfantsUnder5: false,
    address: 'Near Market Square',
    latitude: 25.3120,
    longitude: 82.9825,
    lastVisitDate: '2026-08-21T14:00:00Z',
    lastVisitSeverity: 'low',
    notes: 'Elderly care checkup for grandfather (hypertension on regular medications).'
  },
  {
    id: 'hh-5',
    familyName: 'Ansari Family',
    headOfFamily: 'Mohammad Tariq Ansari',
    village: 'Ramnagar',
    district: 'Varanasi',
    state: 'Uttar Pradesh',
    membersCount: 6,
    hasPregnantMother: false,
    hasInfantsUnder5: true,
    address: 'Ward 2, Weaver Colony',
    latitude: 25.2690,
    longitude: 83.0320,
    lastVisitDate: '2026-08-20T16:20:00Z',
    lastVisitSeverity: 'critical',
    notes: 'Severe Acute Malnutrition (SAM) child Ayush (14mo), weight only 6.2 kg. Referred to NRC.'
  },
  {
    id: 'hh-6',
    familyName: 'Maurya Household',
    headOfFamily: 'Kailash Maurya',
    village: 'Bahadurpur',
    district: 'Varanasi',
    state: 'Uttar Pradesh',
    membersCount: 5,
    hasPregnantMother: true,
    hasInfantsUnder5: false,
    address: 'Village Well Lane',
    latitude: 25.2820,
    longitude: 83.0860,
    lastVisitDate: '2026-08-19T10:00:00Z',
    lastVisitSeverity: 'medium',
    notes: 'Second trimester ANC checkup, IFA tablets issued.'
  }
];

export const DEMO_VISITS: Visit[] = [
  {
    id: 'visit-101',
    workerId: 'asha-1',
    workerName: 'Rani Devi',
    workerVillage: 'Ramnagar',
    householdId: 'hh-1',
    householdName: 'Sharma Family',
    village: 'Ramnagar',
    transcript: 'I visited Sharma family today. Their child Rahul is 3 years old and weighs 9 kilograms. He has fever since yesterday and the mother said he is not eating properly. Provided ORS and paracetamol syrup. Advised sponge baths.',
    structuredData: {
      visitType: 'child_health',
      householdName: 'Sharma Family',
      patientName: 'Rahul Sharma',
      patientCategory: 'child',
      age: 3,
      gender: 'male',
      weightKg: 9,
      temperatureC: 38.6,
      symptoms: ['high fever', 'poor appetite', 'mild lethargy'],
      observations: ['Mild dehydration noted', 'Underweight for 3-year milestone (9kg)'],
      medicationsMentioned: ['Paracetamol syrup 5ml', 'ORS packets'],
      immunizationStatus: 'Up to date with Pentavalent-3 & MR-1',
      referralRequired: false,
      severity: 'medium',
      followUpRequired: true,
      followUpDate: '2026-08-24',
      followUpInstructions: 'Revisit within 48 hours to check fever resolution and appetite recovery.',
      confidence: 0.94
    },
    latitude: 25.2682,
    longitude: 83.0305,
    locationAccuracy: 12,
    timestamp: '2026-08-22T09:30:00Z',
    severity: 'medium',
    status: 'active',
    verificationStatus: 'verified',
    verificationScore: 95,
    verificationReasons: ['GPS accuracy within 12m', 'Normal travel speed', 'Original unique transcript'],
    aiConfidence: 0.94,
    followUpRequired: true,
    followUpDate: '2026-08-24',
    followUpStatus: 'pending',
    createdAt: '2026-08-22T09:32:10Z',
    updatedAt: '2026-08-22T09:32:10Z'
  },
  {
    id: 'visit-102',
    workerId: 'asha-1',
    workerName: 'Rani Devi',
    workerVillage: 'Ramnagar',
    householdId: 'hh-2',
    householdName: 'Yadav Family',
    village: 'Ramnagar',
    transcript: 'Antenatal checkup for Geeta Yadav, 8 months pregnant. Complaining of severe headache and swelling in both feet and face. BP measured 150/95 mmHg. Suspecting pre-eclampsia risk.',
    structuredData: {
      visitType: 'antenatal_care',
      householdName: 'Yadav Family',
      patientName: 'Geeta Yadav',
      patientCategory: 'pregnant_woman',
      age: 24,
      gender: 'female',
      weightKg: 58,
      bloodPressure: '150/95',
      symptoms: ['severe headache', 'blurred vision spells', 'bilateral pedal edema', 'facial puffiness'],
      observations: ['Elevated systolic/diastolic blood pressure', '34 weeks gestation'],
      medicationsMentioned: ['IFA tablets', 'Calcium D3'],
      pregnancyDetails: {
        trimester: 3,
        gestationalWeek: 34,
        bloodPressure: '150/95',
        edemaNoted: true,
        highRiskFlags: ['Pregnancy Induced Hypertension', 'Possible Pre-eclampsia']
      },
      referralRequired: true,
      referralFacility: 'Community Health Centre (CHC) Ramnagar / District Hospital',
      severity: 'high',
      followUpRequired: true,
      followUpDate: '2026-08-23',
      followUpInstructions: 'Urgent escort to CHC for Obstetrician evaluation and urine albumin test.',
      confidence: 0.98
    },
    latitude: 25.2665,
    longitude: 83.0280,
    locationAccuracy: 8,
    timestamp: '2026-08-22T10:15:00Z',
    severity: 'high',
    status: 'active',
    verificationStatus: 'verified',
    verificationScore: 98,
    verificationReasons: ['GPS accurate within 8m', 'High consistency in medical dialogue'],
    aiConfidence: 0.98,
    followUpRequired: true,
    followUpDate: '2026-08-23',
    followUpStatus: 'pending',
    createdAt: '2026-08-22T10:18:00Z',
    updatedAt: '2026-08-22T10:18:00Z'
  },
  {
    id: 'visit-103',
    workerId: 'asha-2',
    workerName: 'Sunita Sharma',
    workerVillage: 'Kalyanpur',
    householdId: 'hh-3',
    householdName: 'Patel Family',
    village: 'Kalyanpur',
    transcript: 'Met with Suman Patel. Her 9-month-old baby girl Ananya is healthy. Checked immunization card. Scheduled for MR-1 vaccine and Vitamin A dose for next session on Tuesday.',
    structuredData: {
      visitType: 'immunization',
      householdName: 'Patel Family',
      patientName: 'Ananya Patel',
      patientCategory: 'infant',
      age: 0.75,
      gender: 'female',
      weightKg: 7.8,
      symptoms: [],
      observations: ['Active and alert', 'Growth curve normal on green zone'],
      medicationsMentioned: ['Vitamin A drops pending'],
      immunizationStatus: 'Due for MR 1st Dose + JE 1st Dose',
      referralRequired: false,
      severity: 'low',
      followUpRequired: true,
      followUpDate: '2026-08-26',
      followUpInstructions: 'Bring child to Anganwadi center for Tuesday immunization session.',
      confidence: 0.96
    },
    latitude: 25.2915,
    longitude: 83.0535,
    locationAccuracy: 15,
    timestamp: '2026-08-21T11:45:00Z',
    severity: 'low',
    status: 'active',
    verificationStatus: 'verified',
    verificationScore: 92,
    verificationReasons: ['Standard visit timeline', 'GPS validated'],
    aiConfidence: 0.96,
    followUpRequired: true,
    followUpDate: '2026-08-26',
    followUpStatus: 'completed',
    createdAt: '2026-08-21T11:48:00Z',
    updatedAt: '2026-08-21T11:48:00Z'
  },
  {
    id: 'visit-104',
    workerId: 'asha-1',
    workerName: 'Rani Devi',
    workerVillage: 'Ramnagar',
    householdId: 'hh-5',
    householdName: 'Ansari Family',
    village: 'Ramnagar',
    transcript: 'Urgent home visit to Ayush Ansari, 14 months old. Child looks very weak, visible muscle wasting and sunken eyes. Weight measured 6.2 kg, MUAC tape shows Red zone 11.2 cm. Mother unable to afford supplementary foods.',
    structuredData: {
      visitType: 'malnutrition',
      householdName: 'Ansari Family',
      patientName: 'Ayush Ansari',
      patientCategory: 'child',
      age: 1.2,
      gender: 'male',
      weightKg: 6.2,
      symptoms: ['extreme weakness', 'loss of appetite', 'chronic diarrhea for 4 days'],
      observations: ['MUAC tape < 11.5 cm (RED BAND - SAM)', 'Severe visible wasting', 'Bipedal edema absent'],
      medicationsMentioned: ['Zinc tablets 20mg', 'ORS'],
      referralRequired: true,
      referralFacility: 'Nutrition Rehabilitation Centre (NRC) Varanasi',
      severity: 'critical',
      followUpRequired: true,
      followUpDate: '2026-08-23',
      followUpInstructions: 'Immediate emergency admission to Nutrition Rehabilitation Centre (NRC). Arrange 108 Ambulance transport.',
      confidence: 0.99
    },
    latitude: 25.2690,
    longitude: 83.0320,
    locationAccuracy: 10,
    timestamp: '2026-08-20T16:20:00Z',
    severity: 'critical',
    status: 'active',
    verificationStatus: 'verified',
    verificationScore: 97,
    verificationReasons: ['High clinical urgency verified by geolocation pin'],
    aiConfidence: 0.99,
    followUpRequired: true,
    followUpDate: '2026-08-23',
    followUpStatus: 'pending',
    createdAt: '2026-08-20T16:25:00Z',
    updatedAt: '2026-08-20T16:25:00Z'
  },
  {
    id: 'visit-105',
    workerId: 'asha-3',
    workerName: 'Pooja Verma',
    workerVillage: 'Shivdaspur',
    householdId: 'hh-4',
    householdName: 'Gupta Family',
    village: 'Shivdaspur',
    transcript: 'Routine follow-up visit completed within 2 minutes without physical patient interaction noted.',
    structuredData: {
      visitType: 'general_checkup',
      householdName: 'Gupta Family',
      patientName: 'Ramesh Gupta',
      patientCategory: 'elderly',
      age: 68,
      gender: 'male',
      symptoms: [],
      observations: ['Brief visit recorded'],
      medicationsMentioned: ['Amlodipine 5mg'],
      referralRequired: false,
      severity: 'low',
      followUpRequired: false,
      confidence: 0.78
    },
    latitude: 25.3120,
    longitude: 82.9825,
    locationAccuracy: 85,
    timestamp: '2026-08-21T14:00:00Z',
    severity: 'low',
    status: 'flagged',
    verificationStatus: 'warning',
    verificationScore: 48,
    verificationReasons: ['Low GPS accuracy (85m)', 'Suspicious short visit duration (< 2 mins)', 'Sparse clinical narrative'],
    aiConfidence: 0.78,
    followUpRequired: false,
    followUpStatus: 'none',
    createdAt: '2026-08-21T14:02:00Z',
    updatedAt: '2026-08-21T14:02:00Z'
  }
];

export const DEMO_ALERTS: HealthAlert[] = [
  {
    id: 'alert-201',
    visitId: 'visit-102',
    workerId: 'asha-1',
    workerName: 'Rani Devi',
    householdId: 'hh-2',
    householdName: 'Yadav Family',
    village: 'Ramnagar',
    severity: 'HIGH',
    title: 'High-Risk Pregnancy: Potential Pre-Eclampsia Detected',
    description: 'Patient Geeta Yadav (34 weeks pregnant) presented with severe headache, facial/pedal edema, and BP 150/95 mmHg.',
    recommendedAction: 'Immediate escort by ASHA worker to Community Health Centre (CHC) for urine protein dipstick and emergency obstetric care.',
    status: 'OPEN',
    createdAt: '2026-08-22T10:18:05Z',
    updatedAt: '2026-08-22T10:18:05Z'
  },
  {
    id: 'alert-202',
    visitId: 'visit-104',
    workerId: 'asha-1',
    workerName: 'Rani Devi',
    householdId: 'hh-5',
    householdName: 'Ansari Family',
    village: 'Ramnagar',
    severity: 'CRITICAL',
    title: 'Severe Acute Malnutrition (SAM) with Complications',
    description: 'Child Ayush Ansari (14 months) weighs 6.2 kg with MUAC in RED band (11.2 cm) and active dehydration.',
    recommendedAction: 'Emergency referral and direct admission to Nutrition Rehabilitation Centre (NRC) District Hospital.',
    status: 'OPEN',
    createdAt: '2026-08-20T16:25:05Z',
    updatedAt: '2026-08-20T16:25:05Z'
  },
  {
    id: 'alert-203',
    visitId: 'visit-105',
    workerId: 'asha-3',
    workerName: 'Pooja Verma',
    householdId: 'hh-4',
    householdName: 'Gupta Family',
    village: 'Shivdaspur',
    severity: 'MEDIUM',
    title: 'Location Verification Anomaly / Short Duration Visit',
    description: 'Visit logged with GPS accuracy exceeding threshold (85m) and reporting duration under 2 minutes.',
    recommendedAction: 'Supervisor follow-up to verify whether physical household visit occurred.',
    status: 'IN_REVIEW',
    acknowledgedBy: 'Dr. Rajesh Sharma',
    supervisorNotes: 'Contacted ASHA Pooja on phone. She clarified poor GPS reception inside brick house. In-person spot check scheduled.',
    createdAt: '2026-08-21T14:05:00Z',
    updatedAt: '2026-08-21T15:30:00Z'
  }
];

export const DEMO_EARNINGS: EarningRecord[] = [
  {
    id: 'earn-1',
    workerId: 'asha-1',
    visitId: 'visit-101',
    taskType: 'ROUTINE_VISIT',
    amount: 50,
    bonus: 15,
    status: 'CREDITED',
    description: 'Child health checkup for Rahul Sharma (Verified with GPS)',
    date: '2026-08-22',
    createdAt: '2026-08-22T09:32:15Z'
  },
  {
    id: 'earn-2',
    workerId: 'asha-1',
    visitId: 'visit-102',
    taskType: 'ANC_PNC',
    amount: 150,
    bonus: 50,
    status: 'CREDITED',
    description: 'High-risk Antenatal care visit & referral escalation for Geeta Yadav',
    date: '2026-08-22',
    createdAt: '2026-08-22T10:18:10Z'
  },
  {
    id: 'earn-3',
    workerId: 'asha-1',
    visitId: 'visit-104',
    taskType: 'HIGH_RISK_FOLLOWUP',
    amount: 120,
    bonus: 40,
    status: 'CREDITED',
    description: 'SAM emergency triage and NRC referral coordination for Ayush Ansari',
    date: '2026-08-20',
    createdAt: '2026-08-20T16:25:10Z'
  },
  {
    id: 'earn-4',
    workerId: 'asha-1',
    taskType: 'IMMUNIZATION',
    amount: 100,
    bonus: 25,
    status: 'DISBURSED',
    description: 'Monthly village immunization drive session completion (14 infants vaccinated)',
    date: '2026-08-15',
    createdAt: '2026-08-15T17:00:00Z'
  },
  {
    id: 'earn-5',
    workerId: 'asha-2',
    visitId: 'visit-103',
    taskType: 'IMMUNIZATION',
    amount: 100,
    bonus: 25,
    status: 'CREDITED',
    description: '9-month immunization scheduling and growth tracking for Ananya Patel',
    date: '2026-08-21',
    createdAt: '2026-08-21T11:48:10Z'
  }
];

export const DEMO_OUTBREAK_CLUSTERS: OutbreakCluster[] = [
  {
    id: 'cluster-1',
    village: 'Ramnagar',
    symptomCategory: 'Acute Febrile Illness / High Fever',
    currentCases: 19,
    historicalBaseline: 4.5,
    riskLevel: 'HIGH',
    trend: 'UPWARD',
    detectedAt: '2026-08-22T08:00:00Z',
    recommendedAction: 'Deploy mobile vector control fogging unit. Initiate rapid dengue/malaria NS1 antigen testing at PHC Ramnagar.',
    affectedVisitsCount: 19,
    status: 'ACTIVE_INVESTIGATION'
  },
  {
    id: 'cluster-2',
    village: 'Shivdaspur',
    symptomCategory: 'Acute Watery Diarrhea & Vomiting',
    currentCases: 14,
    historicalBaseline: 3.2,
    riskLevel: 'HIGH',
    trend: 'UPWARD',
    detectedAt: '2026-08-21T12:00:00Z',
    recommendedAction: 'Chlorinate village water supply well. Distribute halogen tablets and zinc ORS packets house-to-house.',
    affectedVisitsCount: 14,
    status: 'ACTIVE_INVESTIGATION'
  },
  {
    id: 'cluster-3',
    village: 'Kalyanpur',
    symptomCategory: 'Upper Respiratory Tract Infection with Cough',
    currentCases: 8,
    historicalBaseline: 6.0,
    riskLevel: 'LOW',
    trend: 'STABLE',
    detectedAt: '2026-08-19T10:00:00Z',
    recommendedAction: 'Routine surveillance. Advise symptomatic home remedies and monitor for bronchospasm.',
    affectedVisitsCount: 8,
    status: 'MONITORING'
  }
];

export const DEMO_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-1',
    userId: 'dho-1',
    title: 'CRITICAL Alert: SAM Infant in Ramnagar',
    message: 'Ayush Ansari (14mo) identified with MUAC Red Zone (11.2 cm). Emergency NRC admission required.',
    type: 'HIGH_RISK',
    read: false,
    link: '/alerts',
    createdAt: '2026-08-20T16:25:30Z'
  },
  {
    id: 'notif-2',
    userId: 'dho-1',
    title: 'High-Risk Pregnancy Alert',
    message: 'Geeta Yadav (34w gestation) showing BP 150/95 and pedal edema.',
    type: 'HIGH_RISK',
    read: false,
    link: '/alerts',
    createdAt: '2026-08-22T10:18:20Z'
  },
  {
    id: 'notif-3',
    userId: 'asha-1',
    title: 'Incentive Credited: ₹200.00',
    message: '₹150 base + ₹50 timely escalation bonus credited for ANC visit to Yadav family.',
    type: 'EARNING_CREDITED',
    read: true,
    link: '/earnings',
    createdAt: '2026-08-22T10:18:15Z'
  },
  {
    id: 'notif-4',
    userId: 'dho-1',
    title: 'Fever Outbreak Cluster Detected',
    message: 'Ramnagar has 19 active fever cases vs 4.5 baseline (420% spike).',
    type: 'SYSTEM',
    read: false,
    link: '/analytics',
    createdAt: '2026-08-22T08:05:00Z'
  }
];

export const DEMO_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'log-1',
    userId: 'asha-1',
    userName: 'Rani Devi (ASHA)',
    action: 'VISIT_LOGGED_VOICE',
    resource: 'visit-102',
    details: { village: 'Ramnagar', severity: 'high', gpsDistanceMeters: 8 },
    timestamp: '2026-08-22T10:18:00Z'
  },
  {
    id: 'log-2',
    userId: 'system-ai',
    userName: 'Gemini AI Agent',
    action: 'CLINICAL_EXTRACTION_SUCCESS',
    resource: 'visit-102',
    details: { confidence: 0.98, extractedCategory: 'antenatal_care' },
    timestamp: '2026-08-22T10:18:02Z'
  },
  {
    id: 'log-3',
    userId: 'system-agent',
    userName: 'Alert Agent',
    action: 'ALERT_GENERATED',
    resource: 'alert-201',
    details: { severity: 'HIGH', condition: 'Pre-eclampsia risk' },
    timestamp: '2026-08-22T10:18:05Z'
  },
  {
    id: 'log-4',
    userId: 'dho-1',
    userName: 'Dr. Rajesh Sharma (DHO)',
    action: 'ALERT_ACKNOWLEDGED',
    resource: 'alert-203',
    details: { note: 'Spot check scheduled for GPS anomaly.' },
    timestamp: '2026-08-21T15:30:00Z'
  }
];

export const DEMO_PATIENTS: Patient[] = [
  {
    id: 'pat-1',
    householdId: 'hh-1',
    name: 'Rahul Sharma',
    age: 3,
    gender: 'male',
    patientCategory: 'child',
    createdAt: '2026-08-20T08:00:00Z',
    updatedAt: '2026-08-22T09:30:00Z',
    household: DEMO_HOUSEHOLDS[0]
  },
  {
    id: 'pat-2',
    householdId: 'hh-2',
    name: 'Geeta Yadav',
    age: 24,
    gender: 'female',
    patientCategory: 'pregnant_woman',
    createdAt: '2026-08-15T08:00:00Z',
    updatedAt: '2026-08-22T10:15:00Z',
    household: DEMO_HOUSEHOLDS[1]
  },
  {
    id: 'pat-3',
    householdId: 'hh-3',
    name: 'Aayush Maurya',
    age: 0.8,
    gender: 'male',
    patientCategory: 'infant',
    createdAt: '2026-08-18T08:00:00Z',
    updatedAt: '2026-08-22T11:45:00Z',
    household: DEMO_HOUSEHOLDS[2]
  },
  {
    id: 'pat-4',
    householdId: 'hh-4',
    name: 'Lakshmi Devi',
    age: 26,
    gender: 'female',
    patientCategory: 'pregnant_woman',
    createdAt: '2026-08-10T08:00:00Z',
    updatedAt: '2026-08-21T14:20:00Z',
    household: DEMO_HOUSEHOLDS[3]
  },
  {
    id: 'pat-5',
    householdId: 'hh-5',
    name: 'Ramdhani Bind',
    age: 68,
    gender: 'male',
    patientCategory: 'elderly',
    createdAt: '2026-08-12T08:00:00Z',
    updatedAt: '2026-08-20T16:00:00Z',
    household: DEMO_HOUSEHOLDS[4]
  }
];
